version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py
    ports:
     - "8000:5000"
    links:
     - cassandra
  cassandra:
    build:
      context: .
      dockerfile: Dockerfile.db